volumes:
    dblogs:
      name: donkeybot_logs
    dbjson:
      name: donkeybot_json

services:
  donkeybot:
    container_name: donkeybot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app:rw
      - dblogs:/app/logs:rw
      - dbjson:/app/json:rw
    networks:
      - donkeybot

networks:
  donkeybot:
    driver: bridge