volumes:
  donkeybot_logs:
  donkeybot_json:
  anabot_logs:
  anabot_json:

services:
  donkeybot:
    container_name: donkeybot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.donkeybot
    volumes:
      - donkeybot_logs:/app/logs:rw
      - donkeybot_json:/app/json:rw
    networks:
      - botnet

  anabot:
    container_name: anabot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.anabot
    volumes:
      - anabot_logs:/app/logs:rw
      - anabot_json:/app/json:rw
    networks:
      - botnet

  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - .env.donkeybot
    volumes:
      - .:/app:rw
      - donkeybot_logs:/app/logs:rw
      - donkeybot_json:/app/json:rw
    networks:
      - botnet
    profiles:
      - dev

networks:
  botnet:
    driver: bridge
